# Generated by Django 2.2.7 on 2020-04-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assign_cordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('sch_eiin', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='coordiinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='officer_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oname', models.CharField(max_length=100)),
                ('oemail', models.CharField(max_length=100)),
                ('oempid', models.CharField(max_length=50)),
                ('opass', models.CharField(max_length=50)),
                ('oworkp', models.CharField(max_length=50)),
            ],
        ),
    ]
