# Generated by Django 2.2.7 on 2019-11-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='officer_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oname', models.CharField(max_length=100)),
                ('oemail', models.CharField(max_length=100)),
                ('oempid', models.CharField(max_length=50)),
                ('opass', models.CharField(max_length=50)),
                ('oworkp', models.CharField(max_length=50)),
            ],
        ),
    ]
