# Generated by Django 2.2.7 on 2019-12-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0002_coordiinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='assign_cordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('sch_eiin', models.CharField(max_length=20)),
            ],
        ),
    ]
