# Generated by Django 2.2.6 on 2019-11-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=100)),
                ('temail', models.CharField(max_length=254)),
                ('tpass', models.CharField(max_length=50)),
            ],
        ),
    ]
