# Generated by Django 2.2.6 on 2020-06-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_account',
            name='t_phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='teacher_verify',
            name='t_pass',
            field=models.CharField(max_length=11),
        ),
    ]
