# Generated by Django 2.2.7 on 2019-11-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='headmaster_account',
            fields=[
                ('h_fullname', models.CharField(max_length=100)),
                ('h_email', models.CharField(max_length=100)),
                ('h_empid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('h_pass', models.CharField(max_length=50)),
                ('h_school', models.CharField(max_length=250)),
                ('h_phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='student_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_roll', models.CharField(max_length=50)),
                ('s_pass', models.CharField(max_length=50)),
                ('s_class', models.CharField(max_length=10)),
                ('s_school', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_account',
            fields=[
                ('t_fullname', models.CharField(max_length=100)),
                ('t_email', models.CharField(max_length=100)),
                ('t_empid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('t_pass', models.CharField(max_length=50)),
                ('t_school', models.CharField(max_length=250)),
                ('t_phone', models.CharField(max_length=50)),
            ],
        ),
    ]
