# Generated by Django 2.2.7 on 2019-11-28 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_account',
            old_name='StuClass',
            new_name='StuSchool',
        ),
        migrations.RemoveField(
            model_name='student_account',
            name='s_school',
        ),
    ]
