# Generated by Django 2.2.7 on 2019-11-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='headmaster_verify',
            fields=[
                ('h_fullname', models.CharField(max_length=100)),
                ('h_email', models.CharField(max_length=100)),
                ('h_empid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('h_pass', models.CharField(max_length=50)),
                ('h_phone', models.CharField(max_length=50)),
                ('sch_eiin', models.CharField(default=None, max_length=25)),
            ],
        ),
    ]
