# Generated by Django 2.2.7 on 2019-11-28 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('initapp', '0002_auto_20191128_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headmaster_account',
            name='h_school',
        ),
        migrations.RemoveField(
            model_name='teacher_account',
            name='t_school',
        ),
        migrations.AddField(
            model_name='headmaster_account',
            name='h_School',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.schoolInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher_account',
            name='teacherSchool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.schoolInfo'),
            preserve_default=False,
        ),
    ]
