# Generated by Django 2.2.7 on 2019-12-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initapp', '0002_headmaster_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_verify',
            fields=[
                ('t_fullname', models.CharField(max_length=100)),
                ('t_email', models.CharField(max_length=100)),
                ('t_empid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('t_pass', models.CharField(max_length=50)),
                ('t_phone', models.CharField(max_length=50)),
                ('sch_eiin', models.CharField(default=None, max_length=25)),
            ],
        ),
    ]
