# Generated by Django 2.2.7 on 2019-12-07 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20191207_2130'),
        ('initapp', '0003_teacher_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_account',
            name='SchoolEIIN',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='school.schoolInfo'),
            preserve_default=False,
        ),
    ]
