# Generated by Django 2.2.7 on 2019-11-28 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0001_initial'),
        ('initapp', '0003_auto_20191128_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='headmaster_account',
            name='offcr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='officer.officer_account'),
            preserve_default=False,
        ),
    ]
