# Generated by Django 2.2.7 on 2019-12-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initapp', '0004_student_account_schooleiin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_account',
            name='s_class',
            field=models.CharField(choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten')], max_length=10),
        ),
    ]
