# Generated by Django 2.2.7 on 2019-12-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initapp', '0005_auto_20191207_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_account',
            name='SchoolEIIN',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
