# Generated by Django 2.2.7 on 2019-11-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.IntegerField()),
                ('classNumber', models.CharField(choices=[('Class One', 'Class One'), ('Class Two', 'Class Two'), ('Class Three', 'Class Three'), ('Class Four', 'Class Four'), ('Class Five', 'Class Five'), ('Class Six', 'Class Six'), ('Class Seven', 'Class Seven'), ('Class Eight', 'Class Eight'), ('Class Nine', 'Class Nine'), ('Class Ten', 'Class Ten')], max_length=300)),
            ],
        ),
    ]
