# Generated by Django 2.2.7 on 2019-11-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schoolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolId', models.IntegerField()),
                ('schoolName', models.CharField(max_length=100)),
                ('schoolAddress', models.CharField(max_length=100)),
                ('SchoolEIIN', models.CharField(max_length=25)),
                ('totalStudent', models.IntegerField()),
                ('totalTeacher', models.IntegerField()),
            ],
        ),
    ]
