# Generated by Django 2.2.6 on 2019-11-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='schoolinfo',
            name='schoolId',
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='attendance_percentage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='pass_percentage',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='SchoolEIIN',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
