# Generated by Django 2.2.7 on 2019-11-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20191127_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='schoolName',
            field=models.CharField(max_length=300),
        ),
    ]
