# Generated by Django 2.2.7 on 2019-12-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20191129_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='schoolName',
            field=models.CharField(max_length=100),
        ),
    ]
