# Generated by Django 2.2.7 on 2019-12-09 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0006_auto_20191207_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='classSix',
            fields=[
                ('class_no', models.CharField(default=6, max_length=10, primary_key=True, serialize=False)),
                ('total_student', models.IntegerField()),
                ('attendance', models.IntegerField()),
                ('sch_eiin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolInfo')),
            ],
        ),
    ]
