# Generated by Django 2.2.6 on 2019-11-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('school', models.CharField(choices=[('Government Laboratory High School', 'Government Laboratory High School'), ('Viqarunnisa Noon School', 'Viqarunnisa Noon School'), ('Rifles Public School and College', 'Rifles Public School and College'), ('Dhaka Residential Model School and College', 'Dhaka Residential Model School and College'), ('Rajuk Uttara Model School & College', 'Rajuk Uttara Model School & College'), ('Dhanmondi Government Boys’ High School', 'Dhanmondi Government Boys’ High School'), ('Saint Joseph Higher Secondary School', 'Saint Joseph Higher Secondary School'), ('St. Gregory’s High School', 'St. Gregory’s High School'), ('Motijheel Government Boys High school', 'Motijheel Government Boys High school'), ('Mirpur Govt. High School', 'Mirpur Govt. High School'), ('Django', 'Django')], max_length=300)),
            ],
        ),
    ]
