# Generated by Django 2.2.6 on 2020-06-20 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='headmaster_account',
            fields=[
                ('h_fullname', models.CharField(max_length=100)),
                ('h_email', models.CharField(max_length=100)),
                ('h_empid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('dp', models.ImageField(default='default.jpg', upload_to='headmaster')),
                ('h_pass', models.CharField(max_length=50)),
                ('h_phone', models.CharField(max_length=50)),
                ('sch_eiin', models.CharField(default=None, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='headmaster_verify',
            fields=[
                ('h_fullname', models.CharField(max_length=100)),
                ('h_email', models.CharField(max_length=100)),
                ('dp', models.ImageField(default='default.jpg', upload_to='headmaster')),
                ('h_empid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('h_pass', models.CharField(max_length=50)),
                ('h_phone', models.CharField(max_length=50)),
                ('sch_eiin', models.CharField(default=None, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='assign_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=20)),
                ('sch_eiin', models.CharField(default=None, max_length=100)),
                ('t_empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher_account')),
            ],
        ),
    ]
