# Generated by Django 2.2.6 on 2019-12-09 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('initapp', '0006_auto_20191208_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='assign_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=20)),
                ('sch_eiin', models.CharField(default=None, max_length=100)),
                ('t_empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initapp.teacher_account')),
            ],
        ),
    ]
